"use client";
import { useState } from "react";
import { ArrowRight, Box, Mail, MessageSquare, ShieldCheck } from "lucide-react";

export default function Home() {
  const [sent,setSent]=useState(false);
  function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setSent(true);e.currentTarget.reset();setTimeout(()=>document.querySelector('#order')?.scrollIntoView(),50)}
  return <>
    <header className="shell nav"><a className="brand" href="#"><span className="mark">V</span>Vertex</a><nav className="navlinks"><a href="#process">How it works</a><a href="#order">Order</a><a href="/staff">Staff</a><a className="btn btn-dark" href="#order">Start a print <ArrowRight size={17}/></a></nav></header>
    <main>
      <section className="shell hero"><div><p className="eyebrow">Custom 3D printing · Texas</p><h1>Ideas,<br/><em>made real.</em></h1><p className="lead">From useful replacement parts to one-of-a-kind creations, Vertex turns your model into a quality print—with clear updates from quote to delivery.</p><div className="actions"><a className="btn btn-dark" href="#order">Request a quote <ArrowRight size={17}/></a><a className="btn btn-light" href="#process">See the process</a></div></div><div className="hero-art"><span className="chip one"><Box size={15}/> Made layer by layer</span><div className="printer"/><div className="model"/><span className="chip two">Built for your idea</span></div></section>
      <section id="process" className="dark section"><div className="shell"><div className="section-head"><h2>Simple from<br/>start to finish.</h2><p>Tell us what you need. We’ll review the details, send a clear quote, and keep you updated while we make it.</p></div><div className="steps"><article className="step"><span className="step-num">01 · SHARE</span><h3>Send your idea</h3><p>Upload your model or describe what you want. Choose a material, color, and quantity.</p></article><article className="step"><span className="step-num">02 · APPROVE</span><h3>Get a quote</h3><p>We review printability and pricing. Nothing starts until you approve the final quote.</p></article><article className="step"><span className="step-num">03 · CREATE</span><h3>Follow the build</h3><p>Choose email or text updates and know when your print starts, finishes, and ships.</p></article></div></div></section>
      <section id="order" className="shell section"><div className="section-head"><div><p className="eyebrow">Request a quote</p><h2>What can we<br/>make for you?</h2></div><p>No payment is collected here. We’ll review your request and contact you with availability and a quote.</p></div><div className="order-wrap"><aside className="order-note"><h3>Stay in the loop.</h3><p>Choose email, text, or both for updates when your order is quoted, printing, ready, or shipped.</p><p><Mail size={18}/> Email updates<br/><MessageSquare size={18}/> Optional text updates<br/><ShieldCheck size={18}/> Contact details kept private</p></aside><form className="form" onSubmit={submit}>{sent&&<div className="success">Thanks! Your request was recorded for this demo. Live submissions will activate after Vertex’s database is connected.</div>}<div className="grid2"><div className="field"><label htmlFor="name">Full name</label><input id="name" name="name" required placeholder="Your name"/></div><div className="field"><label htmlFor="email">Email</label><input id="email" name="email" type="email" required placeholder="you@example.com"/></div></div><div className="grid2"><div className="field"><label htmlFor="phone">Phone number (optional)</label><input id="phone" name="phone" type="tel" placeholder="(555) 555-5555"/></div><div className="field"><label htmlFor="contact">Update preference</label><select id="contact" name="contact"><option>Email</option><option>Text message</option><option>Email and text</option></select></div></div><div className="grid2"><div className="field"><label htmlFor="material">Material</label><select id="material" name="material"><option>Not sure—help me choose</option><option>PLA</option><option>PETG</option><option>TPU / flexible</option></select></div><div className="field"><label htmlFor="quantity">Quantity</label><input id="quantity" name="quantity" type="number" min="1" defaultValue="1"/></div></div><div className="field"><label htmlFor="details">Tell us about the print</label><textarea id="details" name="details" required placeholder="Size, color, how it will be used, and anything else we should know…"/></div><div className="field"><label htmlFor="model">3D model or reference file (optional)</label><input id="model" name="model" type="file" accept=".stl,.3mf,.obj,.step,.stp,.png,.jpg,.jpeg,.pdf"/></div><button className="btn btn-dark" type="submit">Send quote request <ArrowRight size={17}/></button></form></div></section>
    </main><footer className="shell footer"><div className="brand"><span className="mark">V</span>Vertex</div><span>Custom 3D printing in Texas</span><a className="staff-link" href="/staff">Staff sign in</a></footer>
  </>
}
