"use client";
import { useState } from "react";
import { ArrowRight, CalendarDays, Megaphone, Settings, Tags, Users } from "lucide-react";

type Tab = "Orders" | "Customers" | "Team" | "Discounts" | "Announcements" | "Settings";
const adminTabs: Tab[] = ["Orders", "Customers", "Team", "Discounts", "Announcements", "Settings"];
const employeeTabs: Tab[] = ["Orders", "Announcements", "Settings"];

export default function Staff() {
  const [logged, setLogged] = useState(false);
  const [role, setRole] = useState<"employee" | "admin">("employee");
  const [codeSent, setCodeSent] = useState(false);
  const [activeTab, setActiveTab] = useState<Tab>("Orders");
  const [saved, setSaved] = useState("");

  if (!logged) return <main className="login"><div className="login-card">
    <a className="brand" href="../"><span className="mark">V</span>Vertex</a><h1>Team sign in</h1>
    <p>Employees use an approved account and code. Administrator access stays separate.</p>
    <div className="role-tabs"><button type="button" className={role === "employee" ? "active" : ""} onClick={() => { setRole("employee"); setCodeSent(false); }}>Employee</button><button type="button" className={role === "admin" ? "active" : ""} onClick={() => { setRole("admin"); setCodeSent(false); }}>Administrator</button></div>
    <form onSubmit={e => { e.preventDefault(); if (role === "employee" && !codeSent) { setCodeSent(true); return; } setLogged(true); }}>
      <div className="field"><label>Approved email address</label><input type="email" required placeholder="you@gmail.com" /></div>
      {role === "employee" && !codeSent && <button className="btn btn-dark" type="submit">Send my sign-in code <ArrowRight size={16} /></button>}
      {role === "employee" && codeSent && <><div className="success">Demo: enter the code assigned to this approved employee.</div><div className="field"><label>Employee code</label><input inputMode="numeric" pattern="[0-9]{4}" required placeholder="0000" /></div><button className="btn btn-dark" type="submit">Verify and sign in</button></>}
      {role === "admin" && <><div className="field"><label>Private administrator code</label><input type="password" required placeholder="Enter admin code" /></div><button className="btn btn-dark" type="submit">Enter admin workspace</button></>}
    </form>
  </div></main>;

  const notice = saved && <div className="success">{saved} saved in this demo. Cloud saving activates after Supabase is connected.</div>;
  const visibleTabs = role === "admin" ? adminTabs : employeeTabs;
  return <main className="portal"><div className="portal-grid">
    <aside className="side"><a className="brand" href="../"><span className="mark">V</span>Vertex</a><nav>{visibleTabs.map(tab => <button key={tab} className={activeTab === tab ? "active" : ""} onClick={() => { setActiveTab(tab); setSaved(""); }}>{role === "employee" && tab === "Orders" ? "My orders" : role === "employee" && tab === "Settings" ? "My account" : tab}</button>)}</nav></aside>
    <section className="main"><header className="top"><div><p className="eyebrow">{role === "admin" ? "Admin workspace" : "Employee workspace"}</p><h1>{activeTab}</h1></div>{activeTab === "Orders" && <button className="btn btn-dark">New order</button>}</header>
      {activeTab === "Orders" && <><div className="stats"><article className="stat"><span>{role === "admin" ? "New requests" : "Assigned to me"}</span><strong>{role === "admin" ? "3" : "2"}</strong></article><article className="stat"><span>Currently printing</span><strong>2</strong></article><article className="stat"><span>Ready to ship</span><strong>1</strong></article></div><article className="panel"><h2>{role === "admin" ? "All recent orders" : "My assigned orders"}</h2><table className="table"><thead><tr><th>Order</th>{role === "admin" && <th>Customer</th>}<th>Item</th><th>Status</th><th>Updates</th></tr></thead><tbody><tr><td>#VTX-1042</td>{role === "admin" && <td>Jordan M.</td>}<td>Desk organizer</td><td><span className="pill printing">Printing</span></td><td>Email + text</td></tr><tr><td>#VTX-1041</td>{role === "admin" && <td>Alex R.</td>}<td>Replacement knob</td><td><span className="pill">Awaiting quote</span></td><td>Email</td></tr></tbody></table></article></>}
      {activeTab === "Customers" && <article className="panel"><span className="panel-icon"><Users size={22}/></span><h2>Customers</h2><table className="table"><thead><tr><th>Name</th><th>Contact</th><th>Orders</th><th>Last order</th></tr></thead><tbody><tr><td>Jordan M.</td><td>Email + text</td><td>2</td><td>#VTX-1042</td></tr><tr><td>Alex R.</td><td>Email</td><td>1</td><td>#VTX-1041</td></tr></tbody></table></article>}
      {activeTab === "Team" && <article className="panel"><span className="panel-icon"><Users size={22}/></span><h2>Team members</h2><p className="panel-copy">Promote approved employees up to Manager. Administrator membership remains separate.</p><table className="table"><thead><tr><th>Name</th><th>Gmail</th><th>Level</th><th>Discount</th></tr></thead><tbody><tr><td>Demo Employee</td><td>employee@gmail.com</td><td><select defaultValue="employee"><option>employee</option><option>lead</option><option>manager</option></select></td><td>15%</td></tr></tbody></table></article>}
      {activeTab === "Discounts" && role === "admin" && <div className="panel-stack"><article className="panel discount-panel"><div><span className="panel-icon"><CalendarDays size={22}/></span><h2>Seasonal discount</h2><p>Create a temporary automatic discount for every customer.</p></div><form onSubmit={e=>{e.preventDefault();setSaved("Seasonal discount")}}><div className="grid2"><div className="field"><label>Promotion name</label><input required placeholder="Summer sale"/></div><div className="field"><label>Percent off</label><input required type="number" min="1" max="100" placeholder="15"/></div></div><div className="grid2"><div className="field"><label>Start date</label><input required type="date"/></div><div className="field"><label>End date</label><input required type="date"/></div></div>{saved === "Seasonal discount" && notice}<button className="btn btn-dark">Save seasonal discount</button></form></article><article className="panel discount-panel"><div><span className="panel-icon"><Tags size={22}/></span><h2>Promo code</h2><p>Create a customer code with an expiration and optional use limit.</p></div><form onSubmit={e=>{e.preventDefault();setSaved("Promo code")}}><div className="grid2"><div className="field"><label>Promo code</label><input required minLength={3} maxLength={20} placeholder="VERTEX15" onInput={e=>e.currentTarget.value=e.currentTarget.value.toUpperCase()}/></div><div className="field"><label>Percent off</label><input required type="number" min="1" max="100" placeholder="15"/></div></div><div className="grid2"><div className="field"><label>Expiration date</label><input required type="date"/></div><div className="field"><label>Maximum uses</label><input type="number" min="1" placeholder="Unlimited"/></div></div>{saved === "Promo code" && notice}<button className="btn btn-dark">Create promo code</button></form></article></div>}
      {activeTab === "Announcements" && <article className="panel"><span className="panel-icon"><Megaphone size={22}/></span><h2>Company announcements</h2>{role === "admin" ? <><p className="panel-copy">Create an update for every approved employee.</p><form onSubmit={e=>{e.preventDefault();setSaved("Announcement")}}><div className="field"><label>Subject</label><input required placeholder="Vertex team update"/></div><div className="field"><label>Message</label><textarea required placeholder="Write the announcement…"/></div>{notice}<button className="btn btn-dark">Save announcement draft</button></form></> : <div className="announcement-card"><strong>Welcome to Vertex</strong><p>Company announcements will appear here.</p></div>}</article>}
      {activeTab === "Settings" && <article className="panel"><span className="panel-icon"><Settings size={22}/></span><h2>{role === "admin" ? "Business settings" : "My account"}</h2>{role === "admin" ? <form onSubmit={e=>{e.preventDefault();setSaved("Settings")}}><div className="grid2"><div className="field"><label>Employee discount</label><input type="number" min="0" max="100" defaultValue="15"/></div><div className="field"><label>Order prefix</label><input defaultValue="VTX"/></div></div>{notice}<button className="btn btn-dark">Save settings</button></form> : <div className="account-grid"><p><strong>Level</strong><br/>Employee</p><p><strong>Personal discount</strong><br/>15%</p><p><strong>Approved Gmail</strong><br/>employee@gmail.com</p></div>}</article>}
      <p className="demo-note">Demo data only. Secure cloud data activates after Supabase is connected.</p>
    </section>
  </div></main>;
}
